# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3fc034734f6ab92aceb18e4a22f3ef056e8b8f94cf18870199412069518fbd1fe9e6d39c8df188a34317da1d8166564e79936bde9618eb640abbded5b837176

test:
  secret_key_base: 6a5c1564fe17f3eebe79cdcfd622cc52c986a83dae99b7ef8f1c4bc750f270a34b61e334043cca96d57de307319584622552d78823625a40acca39f48e770d66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
